#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34011
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FarApp.Resource", IsApplication=true)]

namespace FarApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Gcm.Client.Resource.String.library_name = global::FarApp.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int Categories = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060002
			public const int actionBarTabText = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int actionBarTitleText = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int blue = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int color_preloader_center = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int color_preloader_end = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int color_preloader_start = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int darkgray = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int lightblue_text = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int orange = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int spIconColor = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int transparent = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int white = 2131099659;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_orange = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_orange = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_orange = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_orange = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_orange = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_orange = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_cab_done_default_orange = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cab_done_focused_orange = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_orange = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_pressed_orange = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cab_background_bottom_orange = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cab_background_top_orange = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_action_download = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_refresh = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_action_settings = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int list_focused_orange = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int list_pressed_orange = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int menu_dropdown_panel_orange = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int no_image_placeholder = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int orange_arrow = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int progress = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int progress_bg_orange = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int progress_horizontal_orange = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int progress_primary_orange = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int progress_secondary_orange = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int resultItemBackground = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int selectable_background_orange = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int spinner_ab_default_orange = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int spinner_ab_disabled_orange = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int spinner_ab_focused_orange = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int spinner_ab_pressed_orange = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int spinner_background_ab_orange = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int tab_indicator_ab_orange = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int tab_selected_focused_orange = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tab_selected_orange = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tab_selected_pressed_orange = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int tab_unselected_focused_orange = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int tab_unselected_orange = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int tab_unselected_pressed_orange = 2130837542;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public const int Main_Layout = 2131361792;
			
			// aapt resource value: 0x7f0a0007
			public const int details_contacts = 2131361799;
			
			// aapt resource value: 0x7f0a0006
			public const int details_description = 2131361798;
			
			// aapt resource value: 0x7f0a0008
			public const int details_link = 2131361800;
			
			// aapt resource value: 0x7f0a0005
			public const int details_parameters = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int details_price = 2131361796;
			
			// aapt resource value: 0x7f0a0001
			public const int details_progress = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int details_switcher = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int details_title = 2131361795;
			
			// aapt resource value: 0x7f0a0010
			public const int listMenu_old = 2131361808;
			
			// aapt resource value: 0x7f0a000f
			public const int listMenu_refresh = 2131361807;
			
			// aapt resource value: 0x7f0a000b
			public const int resultItem_details = 2131361803;
			
			// aapt resource value: 0x7f0a0009
			public const int resultItem_image = 2131361801;
			
			// aapt resource value: 0x7f0a000c
			public const int resultItem_price = 2131361804;
			
			// aapt resource value: 0x7f0a000a
			public const int resultItem_title = 2131361802;
			
			// aapt resource value: 0x7f0a0011
			public const int settingsMenu = 2131361809;
			
			// aapt resource value: 0x7f0a000d
			public const int settings_list = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int settings_ok = 2131361806;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ResultDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ResultItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Settings = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int ListMenu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int MainMenu = 2131296257;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int ActionBar_Solid_Orange = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int ActionBar_Transparent_Orange = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int ActionBarTabStyle_Orange = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int ActionButton_CloseMode_Orange = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int DropDownListView_Orange = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int DropDownNav_Orange = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int PopupMenu_Orange = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int ProgressBar_Orange = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int Theme_Orange = 2131230720;
			
			// aapt resource value: 0x7f08000a
			public const int Theme_Orange_Widget = 2131230730;
			
			// aapt resource value: 0x7f080002
			public const int TitleColor = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
