#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34011
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FarApp.Resource", IsApplication=true)]

namespace FarApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Gcm.Client.Resource.String.library_name = global::FarApp.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int Categories = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_orange = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_orange = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_orange = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_orange = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_orange = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_orange = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_cab_done_default_orange = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cab_done_focused_orange = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_orange = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_pressed_orange = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cab_background_bottom_orange = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cab_background_top_orange = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int list_focused_orange = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int list_pressed_orange = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int menu_dropdown_panel_orange = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int no_image_placeholder = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int progress_bg_orange = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int progress_horizontal_orange = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int progress_primary_orange = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int progress_secondary_orange = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int selectable_background_orange = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int spinner_ab_default_orange = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int spinner_ab_disabled_orange = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int spinner_ab_focused_orange = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int spinner_ab_pressed_orange = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int spinner_background_ab_orange = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int tab_indicator_ab_orange = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int tab_selected_focused_orange = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int tab_selected_orange = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int tab_selected_pressed_orange = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int tab_unselected_focused_orange = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int tab_unselected_orange = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int tab_unselected_pressed_orange = 2130837537;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int Main_Layout = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int resultItem_details = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int resultItem_image = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int resultItem_price = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int resultItem_title = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int settingsMenu = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int settings_list = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ResultItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Settings = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int MainMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ActionBar_Solid_Orange = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ActionBar_Transparent_Orange = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int ActionBarTabStyle_Orange = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int ActionButton_CloseMode_Orange = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int DropDownListView_Orange = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int DropDownNav_Orange = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int PopupMenu_Orange = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int ProgressBar_Orange = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Orange = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int Theme_Orange_Widget = 2131099657;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
